import { LanguageType } from "./useLanguage";

export const aiReportTranslations = {
  // Dialog Header
  dialogTitle: {
    ar: "رؤى الذكاء الاصطناعي للعقار",
    en: "AI Property Insights",
  },
  dialogDescription: {
    ar: "تقرير مُنشأ بالذكاء الاصطناعي لـ",
    en: "AI-generated report for",
  },
  
  // Actions
  print: {
    ar: "طباعة",
    en: "Print",
  },
  email: {
    ar: "بريد إلكتروني",
    en: "Email",
  },
  sending: {
    ar: "جاري الإرسال...",
    en: "Sending...",
  },
  whatsapp: {
    ar: "واتساب",
    en: "WhatsApp",
  },
  pdf: {
    ar: "PDF",
    en: "PDF",
  },
  tryAgain: {
    ar: "حاول مرة أخرى",
    en: "Try Again",
  },
  
  // Loading/Error States
  analyzingData: {
    ar: "جارٍ تحليل بيانات العقار...",
    en: "Analyzing property data...",
  },
  failedToGenerate: {
    ar: "فشل إنشاء التقرير",
    en: "Failed to generate report",
  },
  
  // Upgrade Notice
  upgradeNotice: {
    ar: "الترقية إلى الباقة الأساسية لتصدير PDF والطباعة والمشاركة، أو البريميوم لإرسالها عبر البريد الإلكتروني",
    en: "Upgrade to Basic to export PDF, print, and share reports, or Premium to email them",
  },
  
  // Print Header
  propertyAIReport: {
    ar: "تقرير الذكاء الاصطناعي للعقار",
    en: "Property AI Report",
  },
  
  // Stats
  safetyRating: {
    ar: "تقييم الأمان",
    en: "Safety Rating",
  },
  marketPrediction: {
    ar: "توقع السوق",
    en: "Market Prediction",
  },
  walkability: {
    ar: "إمكانية المشي",
    en: "Walkability",
  },
  investmentPotential: {
    ar: "الإمكانات الاستثمارية",
    en: "Investment Potential",
  },
  noiseLevel: {
    ar: "مستوى الضوضاء",
    en: "Noise Level",
  },
  airQuality: {
    ar: "جودة الهواء",
    en: "Air Quality",
  },
  traffic: {
    ar: "حركة المرور",
    en: "Traffic",
  },
  restaurants: {
    ar: "المطاعم",
    en: "Restaurants",
  },
  nearby: {
    ar: "قريب",
    en: "nearby",
  },
  confidence: {
    ar: "الثقة",
    en: "confidence",
  },
  
  // Rating Labels
  excellent: {
    ar: "ممتاز",
    en: "Excellent",
  },
  good: {
    ar: "جيد",
    en: "Good",
  },
  fair: {
    ar: "مقبول",
    en: "Fair",
  },
  moderate: {
    ar: "متوسط",
    en: "Moderate",
  },
  poor: {
    ar: "ضعيف",
    en: "Poor",
  },
  high: {
    ar: "عالي",
    en: "High",
  },
  
  // Charts
  overallPropertyScore: {
    ar: "النتيجة الإجمالية للعقار",
    en: "Overall Property Score",
  },
  priceComparison: {
    ar: "مقارنة الأسعار (للمتر المربع)",
    en: "Price Comparison (per sqm)",
  },
  thisProperty: {
    ar: "هذا العقار",
    en: "This Property",
  },
  areaAverage: {
    ar: "متوسط المنطقة",
    en: "Area Average",
  },
  score: {
    ar: "النتيجة",
    en: "Score",
  },
  
  // Chart Metrics
  safety: {
    ar: "الأمان",
    en: "Safety",
  },
  investment: {
    ar: "الاستثمار",
    en: "Investment",
  },
  quietness: {
    ar: "الهدوء",
    en: "Quietness",
  },
  
  // Sections
  areaAnalysis: {
    ar: "تحليل المنطقة",
    en: "Area Analysis",
  },
  investmentAnalysis: {
    ar: "التحليل الاستثماري",
    en: "Investment Analysis",
  },
  futureDevelopments: {
    ar: "التطورات المستقبلية",
    en: "Future Developments",
  },
  
  // Investment
  pricePerSqm: {
    ar: "السعر للمتر المربع",
    en: "Price per sqm",
  },
  rentalYield: {
    ar: "عائد الإيجار",
    en: "Rental yield",
  },
  
  // Amenities
  schools: {
    ar: "المدارس",
    en: "Schools",
  },
  healthcare: {
    ar: "الرعاية الصحية",
    en: "Healthcare",
  },
  shopping: {
    ar: "التسوق",
    en: "Shopping",
  },
  parks: {
    ar: "الحدائق",
    en: "Parks",
  },
  metroStations: {
    ar: "محطات المترو",
    en: "Metro Stations",
  },
  busStops: {
    ar: "محطات الحافلات",
    en: "Bus Stops",
  },
  cinemas: {
    ar: "دور السينما",
    en: "Cinemas",
  },
  sports: {
    ar: "الرياضة",
    en: "Sports",
  },
  connectivity: {
    ar: "الاتصال",
    en: "Connectivity",
  },
  demographics: {
    ar: "التركيبة السكانية",
    en: "Demographics",
  },
  climate: {
    ar: "المناخ",
    en: "Climate",
  },
  
  // Print Footer
  generatedBy: {
    ar: "تم الإنشاء بواسطة SKNAI.xyz - معلومات العقارات السعودية",
    en: "Generated by SKNAI.xyz - Saudi Real Estate Intelligence",
  },
  
  // School Types
  private: {
    ar: "خاص",
    en: "Private",
  },
  public: {
    ar: "عام",
    en: "Public",
  },
  international: {
    ar: "دولي",
    en: "International",
  },
};

export const t = (key: keyof typeof aiReportTranslations, language: LanguageType): string => {
  return aiReportTranslations[key][language];
};