/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type AiReportStatus = "completed" | "failed" | "pending";

export type ControlKeyType = "emergency_shutdown" | "global_distribution_freeze" | "global_issuance_freeze" | "global_trading_freeze";

export type DeletionRequestStatus = "cancelled" | "completed" | "pending";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type InvestorSuitability = "institutional" | "qualified" | "retail";

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type KycStatus = "approved" | "expired" | "pending" | "rejected";

export type LedgerEntryStatus = "confirmed" | "failed" | "pending" | "reversed";

export type LedgerEntryType = "asset_freeze" | "asset_tokenization" | "asset_unfreeze" | "compliance_check" | "emergency_action" | "global_freeze" | "global_unfreeze" | "income_distribution" | "kyc_verification" | "regulatory_override" | "reversal" | "spv_creation" | "token_issuance" | "token_transfer";

export type Numeric = ColumnType<string, number | string, number | string>;

export type OfferingStatus = "closed" | "draft" | "open" | "settled";

export type PaymentStatus = "completed" | "failed" | "pending" | "refunded";

export type PropertyStatus = "available" | "rented" | "sold";

export type PropertyType = "apartment" | "commercial" | "land" | "townhouse" | "villa";

export type SecondaryListingStatus = "active" | "cancelled" | "expired" | "filled";

export type SessionType = "auth" | "temp_oauth";

export type SpvStatus = "active" | "dissolved" | "draft";

export type SubscriptionTier = "basic" | "free" | "premium";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type TokenizationRequestStatus = "approved" | "pending" | "rejected" | "under_review";

export type TokenTransferType = "distribution" | "primary_purchase" | "secondary_buy" | "secondary_sell";

export type UserRole = "admin" | "superadmin" | "user";

export type UserStatus = "active" | "deactivated" | "suspended";

export type WalletTransactionStatus = "completed" | "failed" | "pending";

export type WalletTransactionType = "deposit" | "income_distribution" | "refund" | "token_purchase" | "token_sale" | "withdrawal";

export interface AdminActivityLogs {
  actionType: string;
  adminId: number;
  createdAt: Generated<Timestamp | null>;
  details: Json | null;
  id: Generated<number>;
  ipAddress: string | null;
  targetId: number | null;
  targetType: string | null;
}

export interface AssetControls {
  assetId: number;
  createdAt: Generated<Timestamp>;
  distributionsPaused: Generated<boolean>;
  freezeReason: string | null;
  frozenAt: Timestamp | null;
  frozenBy: number | null;
  id: Generated<number>;
  isFrozen: Generated<boolean>;
  issuancePaused: Generated<boolean>;
  regulatoryHold: Generated<boolean>;
  regulatoryReference: string | null;
  transfersPaused: Generated<boolean>;
  updatedAt: Generated<Timestamp>;
}

export interface ComplianceLogs {
  action: string;
  createdAt: Generated<Timestamp>;
  details: Generated<Json | null>;
  entityId: number | null;
  entityType: string;
  id: Generated<number>;
  ipAddress: string | null;
  userId: number | null;
}

export interface DataDeletionRequests {
  id: Generated<number>;
  notes: string | null;
  processedAt: Timestamp | null;
  requestedAt: Generated<Timestamp>;
  status: Generated<DeletionRequestStatus>;
  userId: number;
}

export interface EmailVerificationCodes {
  code: string;
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: Generated<number>;
  usedAt: Timestamp | null;
  userId: number;
}

export interface GlobalControls {
  activatedAt: Timestamp | null;
  activatedBy: number | null;
  controlKey: ControlKeyType;
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  isActive: Generated<boolean>;
  reason: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface IncomeDistributions {
  amountPerToken: Numeric;
  createdAt: Generated<Timestamp>;
  description: string | null;
  distributionDate: Timestamp;
  id: Generated<number>;
  periodEnd: Timestamp;
  periodStart: Timestamp;
  tokenizedAssetId: number;
  totalAmount: Numeric;
}

export interface InvestorAcknowledgements {
  acknowledgedAt: Generated<Timestamp>;
  acknowledgementType: string;
  id: Generated<number>;
  ipAddress: string | null;
  userId: number;
  version: Generated<string>;
}

export interface InvestorWallets {
  balanceSar: Generated<Numeric>;
  createdAt: Generated<Timestamp>;
  frozenSar: Generated<Numeric>;
  id: Generated<number>;
  totalDeposited: Generated<Numeric>;
  totalIncomeReceived: Generated<Numeric>;
  totalInvested: Generated<Numeric>;
  totalWithdrawn: Generated<Numeric>;
  updatedAt: Generated<Timestamp>;
  userId: number;
}

export interface KycRecords {
  address: string | null;
  createdAt: Generated<Timestamp>;
  dateOfBirth: Timestamp | null;
  expiresAt: Timestamp | null;
  fullNameAr: string | null;
  fullNameEn: string | null;
  id: Generated<number>;
  nationalId: string | null;
  nationality: string | null;
  phone: string | null;
  rejectionReason: string | null;
  riskScore: Generated<number | null>;
  status: Generated<KycStatus>;
  suitability: Generated<InvestorSuitability>;
  updatedAt: Generated<Timestamp>;
  userId: number;
  verifiedAt: Timestamp | null;
}

export interface LedgerEntries {
  assetId: number | null;
  complianceChecks: Generated<Json>;
  contractRuleSet: Generated<string>;
  createdAt: Generated<Timestamp>;
  entryHash: string;
  entryType: LedgerEntryType;
  executedBy: number;
  fromUserId: number | null;
  id: Generated<number>;
  ipAddress: string | null;
  legalReference: string | null;
  metadata: Generated<Json>;
  previousHash: Generated<string>;
  pricePerToken: Numeric | null;
  reversalReason: string | null;
  reversedEntryId: number | null;
  sarAmount: Numeric | null;
  sequenceNumber: Int8;
  spvId: number | null;
  status: Generated<LedgerEntryStatus>;
  tokenAmount: number | null;
  toUserId: number | null;
}

export interface LoginAttempts {
  attemptedAt: Generated<Timestamp | null>;
  email: string;
  id: Generated<number>;
  success: Generated<boolean | null>;
}

export interface OauthAccounts {
  createdAt: Generated<Timestamp | null>;
  id: Generated<number>;
  provider: string;
  providerEmail: string;
  providerUserId: string;
  updatedAt: Generated<Timestamp | null>;
  userId: number;
}

export interface OauthStates {
  codeVerifier: string;
  createdAt: Generated<Timestamp | null>;
  expiresAt: Timestamp;
  id: Generated<number>;
  provider: string;
  redirectUrl: string;
  state: string;
}

export interface Properties {
  aiReportData: Json | null;
  aiReportError: string | null;
  aiReportGeneratedAt: Timestamp | null;
  aiReportStatus: AiReportStatus | null;
  amenities: Generated<string[] | null>;
  areaSqm: Numeric;
  bathrooms: Numeric | null;
  bedrooms: number | null;
  contactPhone: string | null;
  createdAt: Generated<Timestamp | null>;
  description: string | null;
  floorNumber: number | null;
  furnished: Generated<boolean | null>;
  id: Generated<number>;
  images: Generated<string[] | null>;
  isFeatured: Generated<boolean>;
  latitude: Numeric;
  locationName: string;
  longitude: Numeric;
  price: Numeric;
  propertyType: PropertyType;
  status: Generated<PropertyStatus>;
  title: string;
  updatedAt: Generated<Timestamp | null>;
  userId: number;
  yearBuilt: number | null;
  zipCode: string | null;
}

export interface PropertyChats {
  createdAt: Generated<Timestamp | null>;
  deletedByAdmin: Generated<boolean | null>;
  id: Generated<number>;
  message: string;
  propertyId: number;
  updatedAt: Generated<Timestamp | null>;
  userId: number;
}

export interface PropertyViews {
  id: Generated<number>;
  ipAddress: string | null;
  propertyId: number;
  userAgent: string | null;
  userId: number | null;
  viewedAt: Generated<Timestamp>;
}

export interface SecondaryListings {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp | null;
  filledQuantity: Generated<number>;
  id: Generated<number>;
  pricePerToken: Numeric;
  quantity: number;
  sellerId: number;
  status: Generated<SecondaryListingStatus>;
  tokenizedAssetId: number;
  updatedAt: Generated<Timestamp>;
}

export interface Sessions {
  createdAt: Generated<Timestamp | null>;
  expiresAt: Timestamp;
  id: string;
  lastAccessed: Generated<Timestamp | null>;
  sessionType: Generated<SessionType | null>;
  userId: number;
}

export interface SmartContractRules {
  allowedJurisdictions: Generated<string[]>;
  allowedSuitabilities: Generated<string[]>;
  assetId: number;
  autoDistribute: Generated<boolean>;
  canForceTransfer: Generated<boolean>;
  canFreezeIndividualHoldings: Generated<boolean>;
  createdAt: Generated<Timestamp>;
  createdBy: number;
  distributionFrequency: Generated<string>;
  id: Generated<number>;
  maxInvestmentSar: Numeric | null;
  maxInvestors: number | null;
  maxTokenSupply: number;
  minHoldingPeriodDays: Generated<number>;
  minInvestmentSar: Generated<Numeric>;
  requireKyc: Generated<boolean>;
  requireSettlementConfirmation: Generated<boolean>;
  requireSuitabilityCheck: Generated<boolean>;
  ruleVersion: Generated<string>;
  tokensReserved: Generated<number>;
  updatedAt: Generated<Timestamp>;
  withholdingTaxRate: Generated<Numeric>;
}

export interface Spvs {
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  legalDocuments: Generated<Json | null>;
  legalStructure: string | null;
  name: string;
  registrationNumber: string | null;
  status: Generated<SpvStatus>;
  updatedAt: Generated<Timestamp>;
}

export interface SubscriptionPayments {
  amount: Numeric;
  createdAt: Generated<Timestamp | null>;
  currency: Generated<string>;
  expiresAt: Timestamp;
  id: Generated<number>;
  paymentMethod: string | null;
  paymentStatus: Generated<PaymentStatus>;
  startedAt: Generated<Timestamp>;
  tier: SubscriptionTier;
  transactionId: string | null;
  updatedAt: Generated<Timestamp | null>;
  userId: number;
}

export interface TokenHoldings {
  acquiredAt: Generated<Timestamp>;
  averagePurchasePrice: Generated<Numeric>;
  id: Generated<number>;
  quantity: Generated<number>;
  tokenizedAssetId: number;
  totalIncomeReceived: Generated<Numeric>;
  totalInvested: Generated<Numeric>;
  updatedAt: Generated<Timestamp>;
  userId: number;
}

export interface TokenizationRequests {
  adminNotes: string | null;
  createdAt: Generated<Timestamp>;
  desiredTokenPrice: Numeric | null;
  estimatedValue: Numeric | null;
  id: Generated<number>;
  notes: string | null;
  propertyId: number;
  rejectionReason: string | null;
  reviewedAt: Timestamp | null;
  reviewedBy: number | null;
  status: Generated<TokenizationRequestStatus>;
  updatedAt: Generated<Timestamp>;
  userId: number;
}

export interface TokenizedAssets {
  annualRentalYield: Generated<Numeric | null>;
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  incomeRights: Generated<boolean>;
  lockUpDays: Generated<number>;
  offeringStatus: Generated<OfferingStatus>;
  propertyId: number;
  settledAt: Timestamp | null;
  spvId: number;
  titleDeedUrl: string | null;
  tokenPrice: Generated<Numeric>;
  tokensSold: Generated<number>;
  totalTokens: number;
  totalValue: Numeric;
  transferable: Generated<boolean>;
  updatedAt: Generated<Timestamp>;
  valuationReportUrl: string | null;
  votingRights: Generated<boolean>;
  zoningEligible: Generated<boolean>;
}

export interface TokenTransfers {
  createdAt: Generated<Timestamp>;
  fromUserId: number | null;
  id: Generated<number>;
  pricePerToken: Numeric;
  quantity: number;
  tokenizedAssetId: number;
  totalAmount: Numeric;
  toUserId: number;
  transferType: TokenTransferType;
}

export interface UserFavorites {
  createdAt: Generated<Timestamp | null>;
  id: Generated<number>;
  propertyId: number;
  userId: number;
}

export interface UserPasswords {
  createdAt: Generated<Timestamp | null>;
  id: Generated<number>;
  passwordHash: string;
  userId: number;
}

export interface Users {
  aiReportsResetAt: Generated<Timestamp | null>;
  aiReportsUsed: Generated<number>;
  avatarUrl: string | null;
  createdAt: Generated<Timestamp | null>;
  displayName: string;
  email: string;
  emailVerified: Generated<boolean>;
  emailVerifiedAt: Timestamp | null;
  id: Generated<number>;
  phone: string | null;
  role: Generated<UserRole>;
  status: Generated<UserStatus>;
  subscriptionTier: Generated<SubscriptionTier>;
  updatedAt: Generated<Timestamp | null>;
}

export interface WalletTransactions {
  amount: Numeric;
  completedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  description: string | null;
  id: Generated<number>;
  metadata: Generated<Json | null>;
  referenceId: string | null;
  status: Generated<WalletTransactionStatus>;
  type: WalletTransactionType;
  userId: number;
  walletId: number;
}

export interface DB {
  adminActivityLogs: AdminActivityLogs;
  assetControls: AssetControls;
  complianceLogs: ComplianceLogs;
  dataDeletionRequests: DataDeletionRequests;
  emailVerificationCodes: EmailVerificationCodes;
  globalControls: GlobalControls;
  incomeDistributions: IncomeDistributions;
  investorAcknowledgements: InvestorAcknowledgements;
  investorWallets: InvestorWallets;
  kycRecords: KycRecords;
  ledgerEntries: LedgerEntries;
  loginAttempts: LoginAttempts;
  oauthAccounts: OauthAccounts;
  oauthStates: OauthStates;
  properties: Properties;
  propertyChats: PropertyChats;
  propertyViews: PropertyViews;
  secondaryListings: SecondaryListings;
  sessions: Sessions;
  smartContractRules: SmartContractRules;
  spvs: Spvs;
  subscriptionPayments: SubscriptionPayments;
  tokenHoldings: TokenHoldings;
  tokenizationRequests: TokenizationRequests;
  tokenizedAssets: TokenizedAssets;
  tokenTransfers: TokenTransfers;
  userFavorites: UserFavorites;
  userPasswords: UserPasswords;
  users: Users;
  walletTransactions: WalletTransactions;
}


// Use these for zod schema enums or other purposes, since the kysely enums are just types
export const UserRoleArrayValues: [UserRole, ...UserRole[]] = ["admin","superadmin","user"];
export const PropertyTypeArrayValues: [PropertyType, ...PropertyType[]] = ["apartment","commercial","land","townhouse","villa"];
export const PropertyStatusArrayValues: [PropertyStatus, ...PropertyStatus[]] = ["available","rented","sold"];
export const SubscriptionTierArrayValues: [SubscriptionTier, ...SubscriptionTier[]] = ["basic","free","premium"];
export const PaymentStatusArrayValues: [PaymentStatus, ...PaymentStatus[]] = ["completed","failed","pending","refunded"];
export const SessionTypeArrayValues: [SessionType, ...SessionType[]] = ["auth","temp_oauth"];
export const DeletionRequestStatusArrayValues: [DeletionRequestStatus, ...DeletionRequestStatus[]] = ["cancelled","completed","pending"];
export const AiReportStatusArrayValues: [AiReportStatus, ...AiReportStatus[]] = ["completed","failed","pending"];
export const UserStatusArrayValues: [UserStatus, ...UserStatus[]] = ["active","deactivated","suspended"];
export const KycStatusArrayValues: [KycStatus, ...KycStatus[]] = ["approved","expired","pending","rejected"];
export const SpvStatusArrayValues: [SpvStatus, ...SpvStatus[]] = ["active","dissolved","draft"];
export const OfferingStatusArrayValues: [OfferingStatus, ...OfferingStatus[]] = ["closed","draft","open","settled"];
export const TokenTransferTypeArrayValues: [TokenTransferType, ...TokenTransferType[]] = ["distribution","primary_purchase","secondary_buy","secondary_sell"];
export const WalletTransactionTypeArrayValues: [WalletTransactionType, ...WalletTransactionType[]] = ["deposit","income_distribution","refund","token_purchase","token_sale","withdrawal"];
export const WalletTransactionStatusArrayValues: [WalletTransactionStatus, ...WalletTransactionStatus[]] = ["completed","failed","pending"];
export const SecondaryListingStatusArrayValues: [SecondaryListingStatus, ...SecondaryListingStatus[]] = ["active","cancelled","expired","filled"];
export const InvestorSuitabilityArrayValues: [InvestorSuitability, ...InvestorSuitability[]] = ["institutional","qualified","retail"];
export const TokenizationRequestStatusArrayValues: [TokenizationRequestStatus, ...TokenizationRequestStatus[]] = ["approved","pending","rejected","under_review"];
export const LedgerEntryTypeArrayValues: [LedgerEntryType, ...LedgerEntryType[]] = ["asset_freeze","asset_tokenization","asset_unfreeze","compliance_check","emergency_action","global_freeze","global_unfreeze","income_distribution","kyc_verification","regulatory_override","reversal","spv_creation","token_issuance","token_transfer"];
export const LedgerEntryStatusArrayValues: [LedgerEntryStatus, ...LedgerEntryStatus[]] = ["confirmed","failed","pending","reversed"];
export const ControlKeyTypeArrayValues: [ControlKeyType, ...ControlKeyType[]] = ["emergency_shutdown","global_distribution_freeze","global_issuance_freeze","global_trading_freeze"];
// Note: kysely maps the table/column/enum names from snake_case to camelCase and PascalCase. When running SQL statements, make sure to use snake_case, but TypeScript code should use camelCase or PascalCase.