/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type AiReportStatus = "completed" | "failed" | "pending";

export type ControlKeyType = "emergency_shutdown" | "global_distribution_freeze" | "global_issuance_freeze" | "global_trading_freeze";

export type DeletionRequestStatus = "cancelled" | "completed" | "pending";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type InvestorSuitability = "institutional" | "qualified" | "retail";

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type KycStatus = "approved" | "expired" | "pending" | "rejected";

export type LedgerEntryStatus = "confirmed" | "failed" | "pending" | "reversed";

export type LedgerEntryType = "asset_freeze" | "asset_tokenization" | "asset_unfreeze" | "compliance_check" | "emergency_action" | "global_freeze" | "global_unfreeze" | "income_distribution" | "kyc_verification" | "regulatory_override" | "reversal" | "spv_creation" | "token_issuance" | "token_transfer";

export type Numeric = ColumnType<string, number | string, number | string>;

export type OfferingStatus = "closed" | "draft" | "open" | "settled";

export type PaymentStatus = "completed" | "failed" | "pending" | "refunded";

export type PropertyStatus = "available" | "maintenance" | "pending" | "rented" | "sold";

export type PropertyType = "apartment" | "commercial" | "land" | "townhouse" | "villa";

export type SecondaryListingStatus = "active" | "cancelled" | "expired" | "filled";

export type SessionType = "auth" | "temp_oauth";

export type SpvStatus = "active" | "dissolved" | "draft";

export type SubscriptionTier = "basic" | "free" | "premium";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type TokenizationRequestStatus = "approved" | "pending" | "rejected" | "under_review";

export type TokenTransferType = "distribution" | "primary_purchase" | "secondary_buy" | "secondary_sell";

export type UserRole = "admin" | "broker" | "developer" | "owner" | "superadmin" | "user";

export type UserStatus = "active" | "deactivated" | "suspended";

export type WalletTransactionStatus = "completed" | "failed" | "pending";

export type WalletTransactionType = "deposit" | "income_distribution" | "refund" | "token_purchase" | "token_sale" | "withdrawal";

export type RentContractStatus = "active" | "draft" | "expired" | "renewed" | "terminated";

export type RentInvoiceStatus = "cancelled" | "overdue" | "paid" | "partial" | "pending";

export type RentPaymentMethod = "bank_transfer" | "cash" | "check" | "online" | "other" | "payment_link";

export type RentPaymentStatus = "completed" | "failed" | "pending" | "refunded";

export type PaymentIntentStatus = "cancelled" | "created" | "failed" | "processing" | "succeeded";

export type PaymentProviderName = "hyperpay" | "mock" | "moyasar" | "tap";

export type WebhookEventStatus = "failed" | "processed" | "received";

export type ExpenseCategory = "insurance" | "legal" | "maintenance" | "management_fee" | "marketing" | "other" | "repair" | "taxes" | "utilities";

export type DistributionStatus = "completed" | "failed" | "pending" | "processing";

export type AllocationStatus = "confirmed" | "disputed" | "pending";

export type PropertyMemberRole = "broker" | "developer" | "investor" | "owner" | "tenant";
export type FractionalRequestStatus = "pending" | "approved" | "rejected" | "cancelled";
export type FractionalInvestmentStatus = "active" | "exited" | "cancelled" | "pending";
export type RegaFormStatus = "draft" | "completed" | "submitted" | "approved" | "rejected";
export type RegaFormType = "kyc" | "risk_acknowledgment" | "subscription_terms" | "property_listing";
export type TokenTxType = "buy" | "sell" | "transfer" | "distribution" | "mint" | "burn";
export type TokenTxStatus = "pending" | "completed" | "failed" | "cancelled";
export type WorkflowType = "fractional" | "tokenization" | "secondary";

export interface PropertyMembers {
  id: Generated<number>;
  propertyId: number;
  userId: number;
  role: Generated<PropertyMemberRole>;
  grantedBy: number | null;
  createdAt: Generated<Timestamp>;
  updatedAt: Generated<Timestamp>;
}

export interface PropertyUnits {
  areaSqm: Numeric | null;
  bedrooms: number | null;
  bathrooms: Numeric | null;
  createdAt: Generated<Timestamp>;
  description: string | null;
  floorNumber: number | null;
  id: Generated<number>;
  monthlyRent: Generated<Numeric>;
  propertyId: number;
  status: Generated<PropertyStatus>;
  unitNumber: string;
  updatedAt: Generated<Timestamp>;
}

export interface RentalContracts {
  autoGenerateInvoice: Generated<boolean>;
  contractDocumentUrl: string | null;
  contractStatus: Generated<RentContractStatus>;
  createdAt: Generated<Timestamp>;
  endDate: Timestamp;
  id: Generated<number>;
  landlordUserId: number;
  monthlyRent: Numeric;
  notes: string | null;
  paymentDueDay: Generated<number>;
  propertyId: number;
  securityDeposit: Generated<Numeric>;
  startDate: Timestamp;
  tenantUserId: number;
  unitId: number | null;
  updatedAt: Generated<Timestamp>;
}

export interface RentInvoices {
  amount: Numeric;
  contractId: number;
  createdAt: Generated<Timestamp>;
  dueDate: Timestamp;
  id: Generated<number>;
  invoiceStatus: Generated<RentInvoiceStatus>;
  notes: string | null;
  paidAmount: Generated<Numeric>;
  paidAt: Timestamp | null;
  periodEnd: Timestamp;
  periodStart: Timestamp;
  propertyId: number;
  tenantUserId: number;
  updatedAt: Generated<Timestamp>;
}

export interface RentPayments {
  amount: Numeric;
  contractId: number;
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  invoiceId: number;
  notes: string | null;
  paymentDate: Timestamp | null;
  paymentMethod: Generated<RentPaymentMethod>;
  paymentStatus: Generated<RentPaymentStatus>;
  propertyId: number;
  recordedBy: number | null;
  tenantUserId: number;
  transactionReference: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface PaymentIntents {
  amount: Numeric;
  createdAt: Generated<Timestamp>;
  currency: Generated<string>;
  expiresAt: Timestamp | null;
  id: Generated<number>;
  intentStatus: Generated<PaymentIntentStatus>;
  invoiceId: number;
  metadata: Generated<Json>;
  provider: Generated<PaymentProviderName>;
  providerIntentId: string | null;
  paymentUrl: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface PaymentWebhookEvents {
  createdAt: Generated<Timestamp>;
  eventType: string;
  id: Generated<number>;
  payload: Generated<Json>;
  processed: Generated<boolean>;
  processingError: string | null;
  provider: PaymentProviderName;
  providerEventId: string | null;
}

export interface RentReceipts {
  amount: Numeric;
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  invoiceId: number;
  issuedAt: Generated<Timestamp>;
  paymentId: number;
  receiptNumber: string;
  receiptUrl: string | null;
  tenantUserId: number;
}

export interface RentReminders {
  contractId: number;
  createdAt: Generated<Timestamp>;
  deliveryStatus: Generated<string>;
  id: Generated<number>;
  invoiceId: number;
  reminderType: Generated<string>;
  sentAt: Generated<Timestamp>;
}

export interface PropertyOwnershipShares {
  acquiredAt: Generated<Timestamp>;
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  investmentAmount: Generated<Numeric>;
  ownershipPercentage: Numeric;
  propertyId: number;
  updatedAt: Generated<Timestamp>;
  userId: number;
}

export interface PropertyExpenses {
  amount: Numeric;
  category: Generated<ExpenseCategory>;
  createdAt: Generated<Timestamp>;
  description: string | null;
  expenseDate: Timestamp;
  id: Generated<number>;
  propertyId: number;
  receiptUrl: string | null;
  recordedBy: number | null;
  updatedAt: Generated<Timestamp>;
}

export interface RentalIncomeAllocations {
  allocatedAmount: Numeric;
  allocationStatus: Generated<AllocationStatus>;
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  netIncome: Numeric;
  ownerUserId: number;
  ownershipShareId: number | null;
  periodEnd: Timestamp;
  periodStart: Timestamp;
  propertyId: number;
  totalExpenses: Generated<Numeric>;
  totalIncome: Numeric;
  updatedAt: Generated<Timestamp>;
}

export interface InvestorDistributions {
  allocationId: number;
  amount: Numeric;
  createdAt: Generated<Timestamp>;
  distributionDate: Timestamp | null;
  distributionStatus: Generated<DistributionStatus>;
  id: Generated<number>;
  investorUserId: number;
  notes: string | null;
  propertyId: number;
  transactionReference: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface RentAuditLogs {
  action: string;
  createdAt: Generated<Timestamp>;
  details: Generated<Json>;
  entityId: number;
  entityType: string;
  id: Generated<number>;
  ipAddress: string | null;
  userId: number | null;
}

export interface AdminRoleAssignments {
  id: Generated<number>;
  userId: number;
  assignedRole: string;
  assignedBy: number;
  scope: Generated<string>;
  isActive: Generated<boolean>;
  createdAt: Generated<Timestamp>;
  revokedAt: Timestamp | null;
  revokedBy: number | null;
}

export interface UserDashboardPreferences {
  id: Generated<number>;
  userId: number;
  layout: Generated<Json>;
  widgets: Generated<string[]>;
  theme: Generated<string>;
  createdAt: Generated<Timestamp>;
  updatedAt: Generated<Timestamp>;
}

export interface Notifications {
  id: Generated<number>;
  userId: number;
  title: string;
  message: string;
  type: Generated<string>;
  isRead: Generated<boolean>;
  actionUrl: string | null;
  metadata: Generated<Json>;
  createdAt: Generated<Timestamp>;
}

export interface FractionalRequests {
  id: Generated<number>;
  userId: number;
  propertyId: number | null;
  propertyTitle: string;
  city: Generated<string>;
  estimatedValue: Numeric | null;
  fractionalPercent: Numeric | null;
  targetRaise: Numeric | null;
  minimumTicket: Generated<Numeric>;
  incomeModel: string | null;
  useOfFunds: string | null;
  exitPlan: string | null;
  riskSummary: string | null;
  documents: Generated<string[]>;
  regaChecklist: Generated<Json>;
  status: Generated<FractionalRequestStatus>;
  createdAt: Generated<Timestamp>;
  updatedAt: Generated<Timestamp>;
}

export interface FractionalInvestments {
  id: Generated<number>;
  userId: number;
  fractionalRequestId: number;
  amountInvested: Numeric;
  fractionAcquired: Numeric;
  status: Generated<FractionalInvestmentStatus>;
  createdAt: Generated<Timestamp>;
}

export interface PropertyListings {
  id: Generated<number>;
  title: string;
  city: string;
  district: string;
  latitude: Numeric;
  longitude: Numeric;
  price: Numeric;
  type: PropertyType;
  status: Generated<PropertyStatus>;
  bedrooms: number | null;
  areaSqm: Numeric;
  aiScore: Numeric | null;
  descriptionEn: string | null;
  descriptionAr: string | null;
  listedBy: number | null;
  rerReference: string | null;
  createdAt: Generated<Timestamp>;
  updatedAt: Generated<Timestamp>;
}

export interface RegaForms {
  id: Generated<number>;
  userId: number;
  formType: RegaFormType;
  formData: Json;
  status: Generated<RegaFormStatus>;
  createdAt: Generated<Timestamp>;
  updatedAt: Generated<Timestamp>;
}

export interface TokenTransactions {
  id: Generated<number>;
  userId: number;
  tokenizationRequestId: number | null;
  tokenizedAssetId: number | null;
  transactionType: TokenTxType;
  quantity: number;
  pricePerToken: Numeric;
  totalAmount: Numeric;
  status: Generated<TokenTxStatus>;
  metadata: Generated<Json>;
  createdAt: Generated<Timestamp>;
}

export interface WorkflowAudit {
  id: Generated<number>;
  workflow: WorkflowType;
  targetId: string;
  actor: string;
  action: string;
  details: Generated<Json>;
  createdAt: Generated<Timestamp>;
}

export interface AdminActivityLogs {
  actionType: string;
  adminId: number;
  createdAt: Generated<Timestamp | null>;
  details: Json | null;
  id: Generated<number>;
  ipAddress: string | null;
  targetId: number | null;
  targetType: string | null;
  targetUserId: number | null;
  outcome: string | null;
}

export interface AssetControls {
  assetId: number;
  createdAt: Generated<Timestamp>;
  distributionsPaused: Generated<boolean>;
  freezeReason: string | null;
  frozenAt: Timestamp | null;
  frozenBy: number | null;
  id: Generated<number>;
  isFrozen: Generated<boolean>;
  issuancePaused: Generated<boolean>;
  regulatoryHold: Generated<boolean>;
  regulatoryReference: string | null;
  transfersPaused: Generated<boolean>;
  updatedAt: Generated<Timestamp>;
}

export interface ComplianceLogs {
  action: string;
  createdAt: Generated<Timestamp>;
  details: Generated<Json | null>;
  entityId: number | null;
  entityType: string;
  id: Generated<number>;
  ipAddress: string | null;
  userId: number | null;
}

export interface DataDeletionRequests {
  id: Generated<number>;
  notes: string | null;
  processedAt: Timestamp | null;
  requestedAt: Generated<Timestamp>;
  status: Generated<DeletionRequestStatus>;
  userId: number;
}

export interface EmailVerificationCodes {
  code: string;
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: Generated<number>;
  usedAt: Timestamp | null;
  userId: number;
}

export interface GlobalControls {
  activatedAt: Timestamp | null;
  activatedBy: number | null;
  controlKey: ControlKeyType;
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  isActive: Generated<boolean>;
  reason: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface IncomeDistributions {
  amountPerToken: Numeric;
  createdAt: Generated<Timestamp>;
  description: string | null;
  distributionDate: Timestamp;
  id: Generated<number>;
  periodEnd: Timestamp;
  periodStart: Timestamp;
  tokenizedAssetId: number;
  totalAmount: Numeric;
}

export interface InvestorAcknowledgements {
  acknowledgedAt: Generated<Timestamp>;
  acknowledgementType: string;
  id: Generated<number>;
  ipAddress: string | null;
  userId: number;
  version: Generated<string>;
}

export interface InvestorWallets {
  balanceSar: Generated<Numeric>;
  createdAt: Generated<Timestamp>;
  frozenSar: Generated<Numeric>;
  id: Generated<number>;
  totalDeposited: Generated<Numeric>;
  totalIncomeReceived: Generated<Numeric>;
  totalInvested: Generated<Numeric>;
  totalWithdrawn: Generated<Numeric>;
  updatedAt: Generated<Timestamp>;
  userId: number;
}

export interface KycRecords {
  address: string | null;
  createdAt: Generated<Timestamp>;
  dateOfBirth: Timestamp | null;
  expiresAt: Timestamp | null;
  fullNameAr: string | null;
  fullNameEn: string | null;
  id: Generated<number>;
  nationalId: string | null;
  nationality: string | null;
  phone: string | null;
  rejectionReason: string | null;
  riskScore: Generated<number | null>;
  status: Generated<KycStatus>;
  suitability: Generated<InvestorSuitability>;
  updatedAt: Generated<Timestamp>;
  userId: number;
  verifiedAt: Timestamp | null;
}

export interface LedgerEntries {
  assetId: number | null;
  complianceChecks: Generated<Json>;
  contractRuleSet: Generated<string>;
  createdAt: Generated<Timestamp>;
  entryHash: string;
  entryType: LedgerEntryType;
  executedBy: number;
  fromUserId: number | null;
  id: Generated<number>;
  ipAddress: string | null;
  legalReference: string | null;
  metadata: Generated<Json>;
  previousHash: Generated<string>;
  pricePerToken: Numeric | null;
  reversalReason: string | null;
  reversedEntryId: number | null;
  sarAmount: Numeric | null;
  sequenceNumber: Int8;
  spvId: number | null;
  status: Generated<LedgerEntryStatus>;
  tokenAmount: number | null;
  toUserId: number | null;
}

export interface LoginAttempts {
  attemptedAt: Generated<Timestamp | null>;
  email: string;
  id: Generated<number>;
  success: Generated<boolean | null>;
}

export interface OauthAccounts {
  createdAt: Generated<Timestamp | null>;
  id: Generated<number>;
  provider: string;
  providerEmail: string;
  providerUserId: string;
  updatedAt: Generated<Timestamp | null>;
  userId: number;
}

export interface OauthStates {
  codeVerifier: string;
  createdAt: Generated<Timestamp | null>;
  expiresAt: Timestamp;
  id: Generated<number>;
  provider: string;
  redirectUrl: string;
  state: string;
}

export interface Properties {
  aiReportData: Json | null;
  aiReportError: string | null;
  aiReportGeneratedAt: Timestamp | null;
  aiReportStatus: AiReportStatus | null;
  amenities: Generated<string[] | null>;
  areaSqm: Numeric;
  bathrooms: Numeric | null;
  bedrooms: number | null;
  contactPhone: string | null;
  createdAt: Generated<Timestamp | null>;
  description: string | null;
  floorNumber: number | null;
  furnished: Generated<boolean | null>;
  id: Generated<number>;
  images: Generated<string[] | null>;
  isFeatured: Generated<boolean>;
  latitude: Numeric;
  locationName: string;
  longitude: Numeric;
  price: Numeric;
  propertyType: PropertyType;
  status: Generated<PropertyStatus>;
  title: string;
  updatedAt: Generated<Timestamp | null>;
  userId: number;
  yearBuilt: number | null;
  zipCode: string | null;
}

export interface PropertyChats {
  createdAt: Generated<Timestamp | null>;
  deletedByAdmin: Generated<boolean | null>;
  id: Generated<number>;
  message: string;
  propertyId: number;
  updatedAt: Generated<Timestamp | null>;
  userId: number;
}

export interface PropertyViews {
  id: Generated<number>;
  ipAddress: string | null;
  propertyId: number;
  userAgent: string | null;
  userId: number | null;
  viewedAt: Generated<Timestamp>;
}

export interface SecondaryListings {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp | null;
  filledQuantity: Generated<number>;
  id: Generated<number>;
  pricePerToken: Numeric;
  quantity: number;
  sellerId: number;
  status: Generated<SecondaryListingStatus>;
  tokenizedAssetId: number;
  updatedAt: Generated<Timestamp>;
}

export interface Sessions {
  createdAt: Generated<Timestamp | null>;
  expiresAt: Timestamp;
  id: string;
  lastAccessed: Generated<Timestamp | null>;
  sessionType: Generated<SessionType | null>;
  userId: number;
}

export interface SmartContractRules {
  allowedJurisdictions: Generated<string[]>;
  allowedSuitabilities: Generated<string[]>;
  assetId: number;
  autoDistribute: Generated<boolean>;
  canForceTransfer: Generated<boolean>;
  canFreezeIndividualHoldings: Generated<boolean>;
  createdAt: Generated<Timestamp>;
  createdBy: number;
  distributionFrequency: Generated<string>;
  id: Generated<number>;
  maxInvestmentSar: Numeric | null;
  maxInvestors: number | null;
  maxTokenSupply: number;
  minHoldingPeriodDays: Generated<number>;
  minInvestmentSar: Generated<Numeric>;
  requireKyc: Generated<boolean>;
  requireSettlementConfirmation: Generated<boolean>;
  requireSuitabilityCheck: Generated<boolean>;
  ruleVersion: Generated<string>;
  tokensReserved: Generated<number>;
  updatedAt: Generated<Timestamp>;
  withholdingTaxRate: Generated<Numeric>;
}

export interface Spvs {
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  legalDocuments: Generated<Json | null>;
  legalStructure: string | null;
  name: string;
  registrationNumber: string | null;
  status: Generated<SpvStatus>;
  updatedAt: Generated<Timestamp>;
}

export interface SubscriptionPayments {
  amount: Numeric;
  createdAt: Generated<Timestamp | null>;
  currency: Generated<string>;
  expiresAt: Timestamp;
  id: Generated<number>;
  paymentMethod: string | null;
  paymentStatus: Generated<PaymentStatus>;
  startedAt: Generated<Timestamp>;
  tier: SubscriptionTier;
  transactionId: string | null;
  updatedAt: Generated<Timestamp | null>;
  userId: number;
}

export interface TokenHoldings {
  acquiredAt: Generated<Timestamp>;
  averagePurchasePrice: Generated<Numeric>;
  id: Generated<number>;
  quantity: Generated<number>;
  tokenizedAssetId: number;
  totalIncomeReceived: Generated<Numeric>;
  totalInvested: Generated<Numeric>;
  updatedAt: Generated<Timestamp>;
  userId: number;
}

export interface TokenizationRequests {
  adminNotes: string | null;
  createdAt: Generated<Timestamp>;
  desiredTokenPrice: Numeric | null;
  estimatedValue: Numeric | null;
  id: Generated<number>;
  notes: string | null;
  propertyId: number;
  rejectionReason: string | null;
  reviewedAt: Timestamp | null;
  reviewedBy: number | null;
  status: Generated<TokenizationRequestStatus>;
  updatedAt: Generated<Timestamp>;
  userId: number;
}

export interface TokenizedAssets {
  annualRentalYield: Generated<Numeric | null>;
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  incomeRights: Generated<boolean>;
  lockUpDays: Generated<number>;
  offeringStatus: Generated<OfferingStatus>;
  propertyId: number;
  settledAt: Timestamp | null;
  spvId: number;
  titleDeedUrl: string | null;
  tokenPrice: Generated<Numeric>;
  tokensSold: Generated<number>;
  totalTokens: number;
  totalValue: Numeric;
  transferable: Generated<boolean>;
  updatedAt: Generated<Timestamp>;
  valuationReportUrl: string | null;
  votingRights: Generated<boolean>;
  zoningEligible: Generated<boolean>;
}

export interface TokenTransfers {
  createdAt: Generated<Timestamp>;
  fromUserId: number | null;
  id: Generated<number>;
  pricePerToken: Numeric;
  quantity: number;
  tokenizedAssetId: number;
  totalAmount: Numeric;
  toUserId: number;
  transferType: TokenTransferType;
}

export interface UserFavorites {
  createdAt: Generated<Timestamp | null>;
  id: Generated<number>;
  propertyId: number;
  userId: number;
}

export interface UserPasswords {
  createdAt: Generated<Timestamp | null>;
  id: Generated<number>;
  passwordHash: string;
  userId: number;
}

export interface Users {
  aiReportsResetAt: Generated<Timestamp | null>;
  aiReportsUsed: Generated<number>;
  avatarUrl: string | null;
  createdAt: Generated<Timestamp | null>;
  displayName: string;
  email: string;
  emailVerified: Generated<boolean>;
  emailVerifiedAt: Timestamp | null;
  id: Generated<number>;
  phone: string | null;
  role: Generated<UserRole>;
  status: Generated<UserStatus>;
  subscriptionTier: Generated<SubscriptionTier>;
  updatedAt: Generated<Timestamp | null>;
}

export interface WalletTransactions {
  amount: Numeric;
  completedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  description: string | null;
  id: Generated<number>;
  metadata: Generated<Json | null>;
  referenceId: string | null;
  status: Generated<WalletTransactionStatus>;
  type: WalletTransactionType;
  userId: number;
  walletId: number;
}

export interface DB {
  adminActivityLogs: AdminActivityLogs;
  adminRoleAssignments: AdminRoleAssignments;
  assetControls: AssetControls;
  complianceLogs: ComplianceLogs;
  dataDeletionRequests: DataDeletionRequests;
  emailVerificationCodes: EmailVerificationCodes;
  globalControls: GlobalControls;
  incomeDistributions: IncomeDistributions;
  investorAcknowledgements: InvestorAcknowledgements;
  investorWallets: InvestorWallets;
  kycRecords: KycRecords;
  ledgerEntries: LedgerEntries;
  loginAttempts: LoginAttempts;
  oauthAccounts: OauthAccounts;
  notifications: Notifications;
  userDashboardPreferences: UserDashboardPreferences;
  oauthStates: OauthStates;
  properties: Properties;
  propertyListings: PropertyListings;
  propertyChats: PropertyChats;
  propertyExpenses: PropertyExpenses;
  propertyMembers: PropertyMembers;
  propertyOwnershipShares: PropertyOwnershipShares;
  propertyUnits: PropertyUnits;
  propertyViews: PropertyViews;
  investorDistributions: InvestorDistributions;
  fractionalRequests: FractionalRequests;
  fractionalInvestments: FractionalInvestments;
  paymentIntents: PaymentIntents;
  paymentWebhookEvents: PaymentWebhookEvents;
  rentalContracts: RentalContracts;
  rentalIncomeAllocations: RentalIncomeAllocations;
  rentAuditLogs: RentAuditLogs;
  rentInvoices: RentInvoices;
  rentPayments: RentPayments;
  rentReceipts: RentReceipts;
  rentReminders: RentReminders;
  secondaryListings: SecondaryListings;
  sessions: Sessions;
  smartContractRules: SmartContractRules;
  spvs: Spvs;
  subscriptionPayments: SubscriptionPayments;
  tokenHoldings: TokenHoldings;
  tokenizationRequests: TokenizationRequests;
  tokenizedAssets: TokenizedAssets;
  tokenTransfers: TokenTransfers;
  tokenTransactions: TokenTransactions;
  userFavorites: UserFavorites;
  userPasswords: UserPasswords;
  users: Users;
  walletTransactions: WalletTransactions;
  workflowAudit: WorkflowAudit;
}


// Use these for zod schema enums or other purposes, since the kysely enums are just types
export const UserRoleArrayValues: [UserRole, ...UserRole[]] = ["admin","broker","developer","owner","superadmin","user"];
export const PropertyTypeArrayValues: [PropertyType, ...PropertyType[]] = ["apartment","commercial","land","townhouse","villa"];
export const PropertyStatusArrayValues: [PropertyStatus, ...PropertyStatus[]] = ["available","maintenance","pending","rented","sold"];
export const SubscriptionTierArrayValues: [SubscriptionTier, ...SubscriptionTier[]] = ["basic","free","premium"];
export const PaymentStatusArrayValues: [PaymentStatus, ...PaymentStatus[]] = ["completed","failed","pending","refunded"];
export const SessionTypeArrayValues: [SessionType, ...SessionType[]] = ["auth","temp_oauth"];
export const DeletionRequestStatusArrayValues: [DeletionRequestStatus, ...DeletionRequestStatus[]] = ["cancelled","completed","pending"];
export const AiReportStatusArrayValues: [AiReportStatus, ...AiReportStatus[]] = ["completed","failed","pending"];
export const UserStatusArrayValues: [UserStatus, ...UserStatus[]] = ["active","deactivated","suspended"];
export const KycStatusArrayValues: [KycStatus, ...KycStatus[]] = ["approved","expired","pending","rejected"];
export const SpvStatusArrayValues: [SpvStatus, ...SpvStatus[]] = ["active","dissolved","draft"];
export const OfferingStatusArrayValues: [OfferingStatus, ...OfferingStatus[]] = ["closed","draft","open","settled"];
export const TokenTransferTypeArrayValues: [TokenTransferType, ...TokenTransferType[]] = ["distribution","primary_purchase","secondary_buy","secondary_sell"];
export const WalletTransactionTypeArrayValues: [WalletTransactionType, ...WalletTransactionType[]] = ["deposit","income_distribution","refund","token_purchase","token_sale","withdrawal"];
export const WalletTransactionStatusArrayValues: [WalletTransactionStatus, ...WalletTransactionStatus[]] = ["completed","failed","pending"];
export const SecondaryListingStatusArrayValues: [SecondaryListingStatus, ...SecondaryListingStatus[]] = ["active","cancelled","expired","filled"];
export const InvestorSuitabilityArrayValues: [InvestorSuitability, ...InvestorSuitability[]] = ["institutional","qualified","retail"];
export const TokenizationRequestStatusArrayValues: [TokenizationRequestStatus, ...TokenizationRequestStatus[]] = ["approved","pending","rejected","under_review"];
export const LedgerEntryTypeArrayValues: [LedgerEntryType, ...LedgerEntryType[]] = ["asset_freeze","asset_tokenization","asset_unfreeze","compliance_check","emergency_action","global_freeze","global_unfreeze","income_distribution","kyc_verification","regulatory_override","reversal","spv_creation","token_issuance","token_transfer"];
export const LedgerEntryStatusArrayValues: [LedgerEntryStatus, ...LedgerEntryStatus[]] = ["confirmed","failed","pending","reversed"];
export const ControlKeyTypeArrayValues: [ControlKeyType, ...ControlKeyType[]] = ["emergency_shutdown","global_distribution_freeze","global_issuance_freeze","global_trading_freeze"];
export const RentContractStatusArrayValues: [RentContractStatus, ...RentContractStatus[]] = ["active","draft","expired","renewed","terminated"];
export const RentInvoiceStatusArrayValues: [RentInvoiceStatus, ...RentInvoiceStatus[]] = ["cancelled","overdue","paid","partial","pending"];
export const RentPaymentMethodArrayValues: [RentPaymentMethod, ...RentPaymentMethod[]] = ["bank_transfer","cash","check","online","other","payment_link"];
export const RentPaymentStatusArrayValues: [RentPaymentStatus, ...RentPaymentStatus[]] = ["completed","failed","pending","refunded"];
export const PaymentIntentStatusArrayValues: [PaymentIntentStatus, ...PaymentIntentStatus[]] = ["cancelled","created","failed","processing","succeeded"];
export const PaymentProviderNameArrayValues: [PaymentProviderName, ...PaymentProviderName[]] = ["mock","tap","moyasar","hyperpay"];
export const ExpenseCategoryArrayValues: [ExpenseCategory, ...ExpenseCategory[]] = ["insurance","legal","maintenance","management_fee","marketing","other","repair","taxes","utilities"];
export const DistributionStatusArrayValues: [DistributionStatus, ...DistributionStatus[]] = ["completed","failed","pending","processing"];
export const AllocationStatusArrayValues: [AllocationStatus, ...AllocationStatus[]] = ["confirmed","disputed","pending"];
// Note: kysely maps the table/column/enum names from snake_case to camelCase and PascalCase. When running SQL statements, make sure to use snake_case, but TypeScript code should use camelCase or PascalCase.