import React, { useState } from "react";
import { Helmet } from "react-helmet";
import { toast } from "sonner";
import { ArrowLeftRight, CheckCircle2, ShieldCheck } from "lucide-react";
import { Button } from "../components/Button";
import { ComplianceGate } from "../components/ComplianceGate";
import { useAuth } from "../helpers/useAuth";
import { useLanguage } from "../helpers/useLanguage";
import { addWorkflowAudit, saveSecondaryOrder, workflowId } from "../helpers/assetWorkflows";
import styles from "./sakn-flows.module.css";

export default function SecondaryMarketPage() {
  const { language } = useLanguage(); const { authState } = useAuth(); const ar = language === "ar"; const user = authState.type === "authenticated" ? authState.user : null;
  const [form, setForm] = useState({ assetTitle: "", tokenSymbol: "SKNAIA", side: "buy", quantity: "", limitPrice: "", suitabilityConfirmed: false, holdingConfirmed: false, disclosureAccepted: false, coolingOffAccepted: false, bestExecutionNote: "Match against approved order book, price/time priority, manual compliance review before settlement." });
  const set = (key: string, value: string | boolean) => setForm((p)=>({...p,[key]:value}));
  const submit=(e:React.FormEvent)=>{e.preventDefault(); if(!form.suitabilityConfirmed || !form.disclosureAccepted || !form.coolingOffAccepted || (form.side==="sell" && !form.holdingConfirmed)){toast.error(ar?"أكمل ملاءمة المستثمر والإفصاحات وفحص الملكية للبيع":"Complete suitability, disclosures, and holding check for sell orders");return;} const now=new Date().toISOString(); const order={id:workflowId("sec"), investorName:user?.displayName||"Demo Investor", investorEmail:user?.email||"demo@sknai.test", assetTitle:form.assetTitle||"Tokenized asset", tokenSymbol:form.tokenSymbol, side:form.side as "buy"|"sell", quantity:form.quantity, limitPrice:form.limitPrice, suitabilityConfirmed:form.suitabilityConfirmed, holdingConfirmed:form.holdingConfirmed, disclosureAccepted:form.disclosureAccepted, coolingOffAccepted:form.coolingOffAccepted, bestExecutionNote:form.bestExecutionNote, status:"pending_admin_review" as const, createdAt:now, updatedAt:now}; saveSecondaryOrder(order); addWorkflowAudit({workflow:"secondary",targetId:order.id,actor:order.investorEmail,action:"ORDER_SUBMITTED",details:`${order.side} order submitted for admin/best-execution review`}); toast.success(ar?"تم إرسال أمر السوق الثانوية للمراجعة":"Secondary-market order submitted for review");};
  return <div className={styles.page}><Helmet><title>{ar?"السوق الثانوية":"Secondary Market"} | SKNAI</title></Helmet><section className={styles.hero}><span className={styles.eyebrow}><ArrowLeftRight size={16}/> {ar?"أفضل ممارسات السوق الثانوية":"Secondary-market best practices"}</span><h1 className={styles.title}>{ar?"تداول وحدات الملكية بمراجعة امتثال":"Trade ownership units with compliance review"}</h1><p className={styles.subtitle}>{ar?"السوق الثانوية يجب أن تتحقق من ملاءمة المستثمر، الملكية قبل البيع، الإفصاحات، التبريد/الإقرار، وأفضل تنفيذ قبل التسوية.":"Secondary trading requires investor suitability, holding check before sell orders, disclosures, cooling-off acknowledgement, and best-execution review before settlement."}</p></section>
  <section className={styles.section}><div className={styles.grid}>{["Investor suitability and KYC must be approved", "Sell orders require verified token holdings", "Limit orders and price/time priority support fair execution", "Admin review before settlement protects compliance", "Full audit trail for every order event"].map((x,i)=><article className={styles.card} key={x}><div className={styles.cardHeader}><span className={styles.icon}><ShieldCheck size={20}/></span><h3 className={styles.cardTitle}>{ar?`ضابط ${i+1}`:`Control ${i+1}`}</h3></div><p className={styles.cardText}>{x}</p></article>)}</div></section>
  <section className={styles.section}><ComplianceGate featureName={ar?"السوق الثانوية":"Secondary market"}><form className={styles.form} onSubmit={submit}><div className={styles.grid}><article className={styles.card}><h2 className={styles.sectionTitle}>{ar?"أمر تداول":"Trade order"}</h2>{[["assetTitle","Asset title"],["tokenSymbol","Token symbol"],["quantity","Quantity"],["limitPrice","Limit price"]].map(([k,l])=><label className={styles.field} key={k}><span className={styles.label}>{l}</span><input className={styles.input} value={(form as any)[k]} onChange={(e)=>set(k,e.target.value)} /></label>)}<label className={styles.field}><span className={styles.label}>Side</span><select className={styles.select} value={form.side} onChange={(e)=>set("side",e.target.value)}><option value="buy">Buy</option><option value="sell">Sell</option></select></label></article><article className={styles.card}><h2 className={styles.sectionTitle}>{ar?"مراجعات ما قبل التنفيذ":"Pre-trade controls"}</h2>{[["suitabilityConfirmed","Investor suitability confirmed"],["holdingConfirmed","Holding verified for sell orders"],["disclosureAccepted","Secondary-market disclosure accepted"],["coolingOffAccepted","Cooling-off / final confirmation accepted"]].map(([k,l])=><label className={styles.field} key={k}><span><input type="checkbox" checked={(form as any)[k]} onChange={(e)=>set(k,e.target.checked)} /> {l}</span></label>)}<label className={styles.field}><span className={styles.label}>Best-execution note</span><textarea className={styles.textarea} value={form.bestExecutionNote} onChange={(e)=>set("bestExecutionNote",e.target.value)} /></label><Button type="submit"><CheckCircle2 size={16}/> {ar?"إرسال الأمر":"Submit order"}</Button></article></div></form></ComplianceGate></section></div>;
}
