import React, { useState } from "react";
import { Helmet } from "react-helmet";
import { Link } from "react-router-dom";
import { CheckCircle2, Coins, FileCheck2, ShieldCheck } from "lucide-react";
import { toast } from "sonner";
import { Button } from "../components/Button";
import { ComplianceGate } from "../components/ComplianceGate";
import { useAuth } from "../helpers/useAuth";
import { useLanguage } from "../helpers/useLanguage";
import { addWorkflowAudit, emptyRegaChecklist, regaRules, saveTokenizationRequest, workflowId } from "../helpers/assetWorkflows";
import styles from "./sakn-flows.module.css";

export default function TokenizationPage() {
  const { language } = useLanguage();
  const { authState } = useAuth();
  const ar = language === "ar";
  const user = authState.type === "authenticated" ? authState.user : null;
  const [form, setForm] = useState({ propertyTitle: "", assetValue: "", tokenSymbol: "SKNAIA", totalTokens: "10000", tokenPrice: "100", investorCap: "20%", lockupPeriod: "90 days", distributionFrequency: "Quarterly", custodyModel: "Platform ledger + external custodian review", smartContractReview: false, riskSummary: "", docs: "", falLicenseNumber: "", regaAdLicenseNumber: "", brokerageContractNumber: "", ownershipDocumentNumber: "", responsibleOfficer: "", marketingScopeConfirmed: false, adChannelsConfirmed: false, disclosuresAccepted: false });
  const set = (key: string, value: string | boolean) => setForm((p) => ({ ...p, [key]: value }));
  const submit = (event: React.FormEvent) => { event.preventDefault(); if (!form.smartContractReview || !form.marketingScopeConfirmed || !form.disclosuresAccepted) { toast.error(ar ? "أكمل مراجعة العقد والإفصاحات قبل الإرسال" : "Complete contract review and disclosures before submitting"); return; } const now = new Date().toISOString(); const request = { id: workflowId("tok"), applicantName: user?.displayName || "Demo Applicant", applicantEmail: user?.email || "demo@sknai.test", propertyTitle: form.propertyTitle || "Tokenized asset", assetValue: form.assetValue, tokenSymbol: form.tokenSymbol, totalTokens: form.totalTokens, tokenPrice: form.tokenPrice, investorCap: form.investorCap, lockupPeriod: form.lockupPeriod, distributionFrequency: form.distributionFrequency, custodyModel: form.custodyModel, smartContractReview: form.smartContractReview, riskSummary: form.riskSummary, documents: form.docs.split(",").map((d)=>d.trim()).filter(Boolean), rega: { ...emptyRegaChecklist(), falLicenseNumber: form.falLicenseNumber, regaAdLicenseNumber: form.regaAdLicenseNumber, brokerageContractNumber: form.brokerageContractNumber, ownershipDocumentNumber: form.ownershipDocumentNumber, responsibleOfficer: form.responsibleOfficer, marketingScopeConfirmed: form.marketingScopeConfirmed, adChannelsConfirmed: form.adChannelsConfirmed, disclosuresAccepted: form.disclosuresAccepted }, status: "pending_admin_review" as const, createdAt: now, updatedAt: now }; saveTokenizationRequest(request); addWorkflowAudit({ workflow: "tokenization", targetId: request.id, actor: request.applicantEmail, action: "SUBMITTED", details: "Tokenization request submitted with REGA checklist, custody and smart-contract review" }); toast.success(ar ? "تم إرسال طلب الترميز للمراجعة" : "Tokenization request submitted for admin review"); };

  return <div className={styles.page}><Helmet><title>{ar ? "ترميز العقارات" : "Tokenization"} | SKNAI</title></Helmet>
    <section className={styles.hero}><span className={styles.eyebrow}><Coins size={16}/> {ar ? "ترميز منظم" : "Controlled tokenization"}</span><h1 className={styles.title}>{ar ? "حوكمة ترميز العقارات قبل الطرح" : "Real-estate tokenization governance before offering"}</h1><p className={styles.subtitle}>{ar ? "لا يتم إنشاء أو نشر أي طرح رمزي إلا بعد التحقق من الترخيص، الملكية، الإفصاحات، مراجعة العقد الذكي، وموافقة الإدارة." : "No tokenized offering is created or marketed until license, ownership, disclosures, smart-contract review, and admin approval are complete."}</p><div className={styles.actions}><Button asChild><Link to="/admin/tokenization">{ar ? "إدارة الترميز" : "Tokenization admin"}</Link></Button><Button asChild variant="outline"><Link to="/secondary-market">{ar ? "السوق الثانوية" : "Secondary market"}</Link></Button></div></section>
    <section className={styles.section}><div className={styles.grid}>{["Asset eligibility and ownership proof", "Valuation and token economics", "Risk/disclosure pack", "Custody and smart-contract review", "Admin approval before marketing"].map((x,i)=><article className={styles.card} key={x}><div className={styles.cardHeader}><span className={styles.icon}><FileCheck2 size={20}/></span><h3 className={styles.cardTitle}>{ar ? `مرحلة ${i+1}` : `Stage ${i+1}`}</h3></div><p className={styles.cardText}>{x}</p></article>)}</div></section>
    <section className={styles.section}><h2 className={styles.sectionTitle}>{ar ? "كيف يعمل الترميز؟" : "How Tokenization Works"}</h2><div className={styles.timeline}>{[
      {n:1,icon:"🏠",title:ar?"اختيار العقار":'Select Property',desc:ar?"اختر عقاراً مؤهلاً للترميز من محفظتك أو من السوق":"Choose an eligible property from your portfolio or the market"},
      {n:2,icon:"🪙",title:ar?"اقتصاديات الرمز":'Token Economics',desc:ar?"حدد الرمز، العدد، السعر، سقف المستثمرين وفترة القفل":"Set symbol, supply, price, investor cap, and lock-up period"},
      {n:3,icon:"📄",title:ar?"العقد الذكي":'Smart Contract',desc:ar?"تكوين نموذج الحفظ ومراجعة العقد الذكي والقانوني":"Configure custody model and complete smart contract and legal review"},
      {n:4,icon:"✅",title:ar?"امتثال REGA":'REGA Compliance',desc:ar?"النماذج المطلوبة: KYC، المخاطر، الشروط والأحكام، تسجيل RER":"Required forms: KYC, risk acknowledgment, terms, RER registration"},
      {n:5,icon:"🚀",title:ar?"الإطلاق":'Go Live',desc:ar?"بعد موافقة الإدارة تصبح الرموز متاحة للتداول في السوق الثانوي":"After admin approval, tokens go live for trading on the secondary market"},
    ].map(s=><div className={styles.step} key={s.n}><span className={styles.stepNumber}>{s.n}</span><div><strong>{s.icon} {s.title}</strong><p className={styles.cardText}>{s.desc}</p></div></div>)}</div></section>
    <section className={styles.section}><ComplianceGate featureName={ar ? "طلب الترميز" : "Tokenization request"}><form className={styles.form} onSubmit={submit}><div className={styles.grid}>
      <article className={styles.card}><h2 className={styles.sectionTitle}>{ar ? "اقتصاديات الرمز" : "Token economics"}</h2>{[["propertyTitle","Property title"],["assetValue","Asset value"],["tokenSymbol","Token symbol"],["totalTokens","Total tokens"],["tokenPrice","Token price"],["investorCap","Investor cap"],["lockupPeriod","Lock-up period"],["distributionFrequency","Distribution frequency"]].map(([k,l])=><label className={styles.field} key={k}><span className={styles.label}>{l}</span><input className={styles.input} value={(form as any)[k]} onChange={(e)=>set(k,e.target.value)} /></label>)}</article>
      <article className={styles.card}><h2 className={styles.sectionTitle}>{ar ? "الحفظ والمخاطر" : "Custody and risk"}</h2><label className={styles.field}><span className={styles.label}>Custody model</span><textarea className={styles.textarea} value={form.custodyModel} onChange={(e)=>set("custodyModel",e.target.value)} /></label><label className={styles.field}><span className={styles.label}>Risk summary</span><textarea className={styles.textarea} value={form.riskSummary} onChange={(e)=>set("riskSummary",e.target.value)} /></label><label className={styles.field}><span><input type="checkbox" checked={form.smartContractReview} onChange={(e)=>set("smartContractReview",e.target.checked)} /> Smart-contract/legal review completed</span></label></article>
      <article className={styles.card}><h2 className={styles.sectionTitle}><ShieldCheck size={20}/> REGA/FAL</h2>{[["falLicenseNumber","FAL / REGA license #"],["regaAdLicenseNumber","Ad license #"],["brokerageContractNumber","Brokerage/marketing contract #"],["ownershipDocumentNumber","Ownership document #"],["responsibleOfficer","Responsible officer"]].map(([k,l])=><label className={styles.field} key={k}><span className={styles.label}>{l}</span><input className={styles.input} value={(form as any)[k]} onChange={(e)=>set(k,e.target.value)} /></label>)}{[["marketingScopeConfirmed","License scope confirmed"],["adChannelsConfirmed","Channels approved"],["disclosuresAccepted","Disclosure pack accepted"]].map(([k,l])=><label className={styles.field} key={k}><span><input type="checkbox" checked={(form as any)[k]} onChange={(e)=>set(k,e.target.checked)} /> {l}</span></label>)}</article>
      <article className={styles.card}><h2 className={styles.sectionTitle}>{ar ? "المستندات والإرسال" : "Documents and submit"}</h2><label className={styles.field}><span className={styles.label}>Documents</span><textarea className={styles.textarea} value={form.docs} onChange={(e)=>set("docs",e.target.value)} placeholder="valuation.pdf, title-deed.pdf, smart-contract-review.pdf" /></label><div className={styles.badgeRow}>{regaRules.slice(0,3).map(r=><span className={styles.badge} key={r}>REGA gate</span>)}</div><Button type="submit"><CheckCircle2 size={16}/> {ar ? "إرسال للمراجعة" : "Submit for review"}</Button></article>
    </div></form></ComplianceGate></section>
  </div>;
}
